### PR TITLE
Added Font size preferences

### PR DESCRIPTION
**Pull request by ImperialOsprey4**
Hi Guys!
I've worked on implementing font size preference, hope you like it.
If you have any recommendation or improvement I will be happy to read you 😄 

Alt Text

### CODE REVIEW

**Comment by sarthology** [comment]
Hey 👋
Thanks a lot for your PR. 😊
Can you add Gif in the Description?

**Comment by ImperialOsprey4** [comment]
Of course 😃

**Comment by sarthology** [comment]
Lol, I mean of the feature.

**Comment by ImperialOsprey4** [comment]
I should have guessed :satisfied:

**Comment by ImperialOsprey4** [comment]
Any improvement?

**Pull request closed without merging**
